### ISSUE TITLE
Converting a .ckpt to .pb [Basic help]

### ISSUE THREAD

**Issue by ghost** [tzattack/tensorflow_ckpt_2_pb#2]
@tzattack Thank you for your hard work,
How can I convert [resnet_v1_50.ckpt](http://download.tensorflow.org/models/resnet_v1_50_2016_08_28.tar.gz) to `.pb`?

```
python ckpt2pb.py ./resnet_v1_50.ckpt 
Traceback (most recent call last):
  File "ckpt2pb.py", line 48, in <module>
    freeze_graph(aggs.model_folder)
  File "ckpt2pb.py", line 16, in freeze_graph
    input_checkpoint = checkpoint.model_checkpoint_path #得ckpt文件路径
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'
```

**Comment by huiofficial** [comment]
did you addd ckpt path?

**Comment by ghost** [comment]
yes

**Comment by trihook** [comment]
same problem of mine

**Comment by huiofficial** [comment]
You need to freeze your network graph first, then you can convert ckpt to pb.
